notifications:
  email:
    - bart@triquanta.nl
    - jur@triquanta.nl

language: php

php:
  - 5.4
  - 5.5
  - 5.6

script:
  - cd $TRAVIS_BUILD_DIR/application
  - composer install
  - vendor/bin/phpunit -c ./phpunit.xml.dist --bootstrap ./tests/bootstrap.php --verbose --debug || exit 1
