Vagrant.configure("2") do |config|
  ## Choose your base box
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "192.168.50.5"

#   config.vm.synced_folder "../application", "/opt/siteinspector"
  config.vm.synced_folder "..", "/opt/accessibilitymonitor"

  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key']
  config.ssh.forward_agent = true

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "servercontrol/install.yaml"
    ansible.inventory_path = "ansible_hosts"
    ansible.sudo = true
    ansible.limit = 'all'
  end
end
